export const CHANGE_VIEW = "CHANGE_VIEW";

export const ADD_REMINDER = "ADD_REMINDER";
export const UPDATE_REMINDER = "UPDATE_REMINDER";

export const CHANGE_DATE = "CHANGE_DATE";

export const TOGGLE_CREATING_REMINDER = "TOGGLE_CREATING_REMINDER";
